version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest test_basic_function.py test_synthetic_data.py test_duration_calc.py

workflows:
  version: 2
  build:
    jobs:
      - build
